name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '23 8 * * *'

permissions:
  contents: read

jobs:
  conformance:
    uses: ./.github/workflows/conformance.yml
